# Generated by Django 4.2.3 on 2023-08-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('easy_drive_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.URLField(max_length=205)),
                ('additional_photo', models.URLField(max_length=205)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=350)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_drive_profile.profile')),
            ],
        ),
    ]
